AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Bot-ARTF

Globals:
  Function:
    Timeout: 9
    Runtime: python3.9
    MemorySize: 256
    Architectures:
      - x86_64

Resources:
  PTBFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ptb/
      Handler: ptb_lambda.lambda_handler
      Policies:
          - RekognitionDetectOnlyPolicy: {}
          - Statement:
            - Effect: "Allow"
              Action:
                - ssm:GetParameters
                - ssm:GetParameter
                - ssm:GetParametersByPath
              Resource:
                - '*'
                - 'arn:aws:ssm:::parameter/telegramartfbot/*'
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  TelegramApi:
    Description: "Lambda URL for PTB function"
    Value:
      Fn::GetAtt: PTBFunctionUrl.FunctionUrl
